import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "~/components/ui/card";

import Head from "next/head";
import Image from "next/image";

import { useRouter } from "next/router";
import { type SimplifiedPlaylist } from "spotify-web-api-ts/types/types/SpotifyObjects";
import { Button } from "~/components/ui/button";
import { api } from "~/utils/api";

export default function Home() {
  const { data } = api.spotify.getUsersPlaylist.useQuery();
  return (
    <>
      <Head>
        <title>Create T3 App Test</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mt-5  flex min-h-screen justify-center">
        <div className="grid h-fit grid-cols-3  gap-5">
          {data?.playlists.items.map((playlist) => (
            <PlaylistCard playlist={playlist} key={playlist.id} />
          ))}
        </div>
      </main>
    </>
  );
}
const PlaylistCard = ({ playlist }: { playlist: SimplifiedPlaylist }) => {
  const router = useRouter();
  return (
    <Card>
      <CardHeader></CardHeader>
      <CardContent>
        <div className=" flex gap-2">
          <Image
            alt={playlist.images?.[0]?.url ?? ""}
            src={playlist.images?.[0]?.url ?? ""}
            layout="fixed"
            width={50}
            height={50}
            style={{
              width: "50px",
              height: "auto",
              backgroundSize: "cover",
            }}
          />
          <div className="flex flex-col gap-2">
            <CardTitle>{playlist.name} </CardTitle>
            <CardDescription>{playlist.tracks.total} Titel</CardDescription>
          </div>
        </div>
      </CardContent>
      <CardFooter className="  w-full ">
        <Button
          className="mt-5 w-full "
          onClick={() => router.push("playlist/" + playlist.id)}
        >
          Sync
        </Button>
      </CardFooter>
    </Card>
  );
};
